[package]
name = "nix-seal-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.12"
nix-seal-core = { path = "../crates/nix-seal-core" }
nix-seal-manifest = { path = "../crates/nix-seal-manifest" }
nix-seal-policy = { path = "../crates/nix-seal-policy" }
nix-seal-runtime = { path = "../crates/nix-seal-runtime" }
serde_json = "1.0"

[[bin]]
name = "plan-v1"
path = "fuzz_targets/plan_v1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "artifact-envelope-v1"
path = "fuzz_targets/artifact_envelope_v1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "activation-v2"
path = "fuzz_targets/activation_v2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "template-v1"
path = "fuzz_targets/template_v1.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
